name = 'Exformal records website theme'
license = 'MIT'
licenselink = 'https://github.com/madskjeldgaard/exformal-hugo-theme/LICENSE'
description = 'A theme for record labels/artists/weirdos'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/madskjeldgaard/exformal-hugo-theme'

# If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'company', 'record label', 'artist', 'weirdo', 'portfolio']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Mads Kjeldgaard'
  homepage = 'https://madskjeldgaard.dk'
